[build-system]
# Minimum requirements for the build system to execute.

requires = [
    "setuptools>=51.0.0",
    "wheel",
    "numpy>=1.4.3", 
    "pandas>=1.2"
]

build-backend = "setuptools.build_meta"

